# Default configuration (common across all profiles)
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/default_db
    username: root
    password: root
  profiles:
    active: dev  # Default active profile

# Development profile
---
spring:
  config:
    activate:
      on-profile: dev
  datasource:
    url: jdbc:mysql://localhost:3306/dev_db
    username: dev_user
    password: dev_password
  server:
    port: 8080

# Testing profile
---
spring:
  config:
    activate:
      on-profile: test
  datasource:
    url: jdbc:mysql://localhost:3306/test_db
    username: test_user
    password: test_password
  server:
    port: 8081

# Production profile
---
spring:
  config:
    activate:
      on-profile: prod
  datasource:
    url: jdbc:mysql://localhost:3306/prod_db
    username: prod_user
    password: prod_password
  server:
    port: 8082
    ssl:
      enabled: true
